#! /bin/sh

CFGDIR=$HOME/.config


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           15
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



for PROCESS in sxhkd compton albert polybar
do
    pkill $PROCESS
done

feh --bg-center /home/justin/Wallpapers/small-memory-lp.jpg

sxhkd &
compton --config $CFGDIR/compton/compton.conf -b
albert &
# polybar -c $CFGDIR/polybar/gamehelp16_config top &
