#! /bin/sh

bspc config border_width         3
bspc config window_gap           15
bspc config top_padding          10  # for polybar

bspc config focused_border_color "#005D8C"

bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

for side in top right bottom left
do
    bspc config ${side}_monocle_padding -$(bspc config ${side}_padding)
done

# machine-specific monitor/keyboard options
case $(cat /var/lib/dbus/machine-id) in
    3b5960f4107945baadd780fd5696cf14)  # home
        xrandr --output DP-4 --mode 3440x1440 --rate 144
        bspc monitor -d 1 2 3 4 5 6 7 8 9
        ;;
    ed0adf4708574812a27a4a6930a9acc6)  # work
        bspc monitor DP-1-1-1 -d 1 2 3
        bspc monitor DP-1-1-2 -d 4 5 6
        bspc monitor eDP-1-1 -d 7 8 9
        xrandr --output eDP-1-1 --mode 1920x1080
        xrandr --output DP-1-1-2 --above eDP-1-1
        xrandr --output DP-1-1-1 --left-of DP-1-1-2
        setxkbmap -layout us -option ctrl:nocaps
        setxkbmap -layout us -option altwin:swap_alt_win
        ;;
    *)
        bspc monitor -d I II III IV V VI VII VIII IX X
        ;;
esac

for PROCESS in sxhkd compton polybar
do
    pkill $PROCESS
done

feh --bg-scale ~/Wallpapers/wallpaper.jpg

CFGDIR=~/.config
sxhkd -c $CFGDIR/sxhkd/sxhkdrc &
compton --config $CFGDIR/compton/compton.conf -b

for MONITOR in $(polybar --list-monitors | awk -F':' '{print $1}')
do
    MONITOR=$MONITOR polybar --config=$CFGDIR/polybar/config example &
done
